// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xcalc_hog.h"

extern XCalc_hog_Config XCalc_hog_ConfigTable[];

XCalc_hog_Config *XCalc_hog_LookupConfig(u16 DeviceId) {
	XCalc_hog_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XCALC_HOG_NUM_INSTANCES; Index++) {
		if (XCalc_hog_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XCalc_hog_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XCalc_hog_Initialize(XCalc_hog *InstancePtr, u16 DeviceId) {
	XCalc_hog_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XCalc_hog_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XCalc_hog_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

