// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xcalc_hog.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XCalc_hog_CfgInitialize(XCalc_hog *InstancePtr, XCalc_hog_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_bus_BaseAddress = ConfigPtr->Control_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XCalc_hog_Start(XCalc_hog *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCalc_hog_ReadReg(InstancePtr->Control_bus_BaseAddress, XCALC_HOG_CONTROL_BUS_ADDR_AP_CTRL) & 0x80;
    XCalc_hog_WriteReg(InstancePtr->Control_bus_BaseAddress, XCALC_HOG_CONTROL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XCalc_hog_IsDone(XCalc_hog *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCalc_hog_ReadReg(InstancePtr->Control_bus_BaseAddress, XCALC_HOG_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XCalc_hog_IsIdle(XCalc_hog *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCalc_hog_ReadReg(InstancePtr->Control_bus_BaseAddress, XCALC_HOG_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XCalc_hog_IsReady(XCalc_hog *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCalc_hog_ReadReg(InstancePtr->Control_bus_BaseAddress, XCALC_HOG_CONTROL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XCalc_hog_EnableAutoRestart(XCalc_hog *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCalc_hog_WriteReg(InstancePtr->Control_bus_BaseAddress, XCALC_HOG_CONTROL_BUS_ADDR_AP_CTRL, 0x80);
}

void XCalc_hog_DisableAutoRestart(XCalc_hog *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCalc_hog_WriteReg(InstancePtr->Control_bus_BaseAddress, XCALC_HOG_CONTROL_BUS_ADDR_AP_CTRL, 0);
}

void XCalc_hog_Set_imageptr(XCalc_hog *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCalc_hog_WriteReg(InstancePtr->Control_bus_BaseAddress, XCALC_HOG_CONTROL_BUS_ADDR_IMAGEPTR_DATA, Data);
}

u32 XCalc_hog_Get_imageptr(XCalc_hog *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCalc_hog_ReadReg(InstancePtr->Control_bus_BaseAddress, XCALC_HOG_CONTROL_BUS_ADDR_IMAGEPTR_DATA);
    return Data;
}

void XCalc_hog_Set_feature_r(XCalc_hog *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCalc_hog_WriteReg(InstancePtr->Control_bus_BaseAddress, XCALC_HOG_CONTROL_BUS_ADDR_FEATURE_R_DATA, Data);
}

u32 XCalc_hog_Get_feature_r(XCalc_hog *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCalc_hog_ReadReg(InstancePtr->Control_bus_BaseAddress, XCALC_HOG_CONTROL_BUS_ADDR_FEATURE_R_DATA);
    return Data;
}

void XCalc_hog_InterruptGlobalEnable(XCalc_hog *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCalc_hog_WriteReg(InstancePtr->Control_bus_BaseAddress, XCALC_HOG_CONTROL_BUS_ADDR_GIE, 1);
}

void XCalc_hog_InterruptGlobalDisable(XCalc_hog *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCalc_hog_WriteReg(InstancePtr->Control_bus_BaseAddress, XCALC_HOG_CONTROL_BUS_ADDR_GIE, 0);
}

void XCalc_hog_InterruptEnable(XCalc_hog *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XCalc_hog_ReadReg(InstancePtr->Control_bus_BaseAddress, XCALC_HOG_CONTROL_BUS_ADDR_IER);
    XCalc_hog_WriteReg(InstancePtr->Control_bus_BaseAddress, XCALC_HOG_CONTROL_BUS_ADDR_IER, Register | Mask);
}

void XCalc_hog_InterruptDisable(XCalc_hog *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XCalc_hog_ReadReg(InstancePtr->Control_bus_BaseAddress, XCALC_HOG_CONTROL_BUS_ADDR_IER);
    XCalc_hog_WriteReg(InstancePtr->Control_bus_BaseAddress, XCALC_HOG_CONTROL_BUS_ADDR_IER, Register & (~Mask));
}

void XCalc_hog_InterruptClear(XCalc_hog *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCalc_hog_WriteReg(InstancePtr->Control_bus_BaseAddress, XCALC_HOG_CONTROL_BUS_ADDR_ISR, Mask);
}

u32 XCalc_hog_InterruptGetEnabled(XCalc_hog *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCalc_hog_ReadReg(InstancePtr->Control_bus_BaseAddress, XCALC_HOG_CONTROL_BUS_ADDR_IER);
}

u32 XCalc_hog_InterruptGetStatus(XCalc_hog *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCalc_hog_ReadReg(InstancePtr->Control_bus_BaseAddress, XCALC_HOG_CONTROL_BUS_ADDR_ISR);
}

